export const NOTES_REQUEST = "NOTES_REQUEST";
export const NOTES_SUCCESS = "NOTES_SUCCESS";
export const NOTES_FAIL = "NOTES_FAIL";

export const NOTE_CREATE_REQUEST = "NOTE_CREATE_REQUEST";
export const NOTE_CREATE_SUCCESS = "NOTE_CREATE_SUCCESS";
export const NOTE_CREATE_FAIL = "NOTES_CREATE_FAIL";

export const NOTE_EDIT_REQUEST = "NOTE_EDIT_REQUEST";
export const NOTE_EDIT_SUCCESS = "NOTE_EDIT_SUCCESS";
export const NOTE_EDIT_FAIL = "NOTES_EDIT_FAIL";

export const NOTE_DELETE_REQUEST = "NOTE_DELETE_REQUEST";
export const NOTE_DELETE_SUCCESS = "NOTE_DELETE_SUCCESS";
export const NOTE_DELETE_FAIL = "NOTES_DELETE_FAIL";